---
- name:  Creating server profile templates from csv
  hosts: localhost
  vars:
     config: 'oneview_config.json'
  tasks:


     - name: Get uri of serverhardware type SY 480 Gen10 1       
       oneview_server_hardware_type_facts:           
         config:   '{{ config }}'                  
         name:     SY 480 Gen10 1                                
     - set_fact:                                     
         var_SY_480_Gen10_1_uri    :       '{{server_hardware_types[0].uri}}' 




     - name: Create server profile template HPE Synergy 480 Gen10 with Local Boot for RSOE Template       
       oneview_server_profile_template:              
         config:     '{{ config }}'                
         state:      present                         
         data:                                       
             name:                       'HPE Synergy 480 Gen10 with Local Boot for RSOE Template'      
             type:                       'ServerProfileTemplateV7'      
             description:                'Server Profile for HPE Synergy 480 Gen10 Compute Module with Local Boot for RSOE'      
             serverProfileDescription:   'Server Profile for HPE Synergy 480 Gen10 Compute Module with Local Boot for RSOE'      
             serverHardwareTypeUri:        '{{var_SY_480_Gen10_1_uri}}'            
             enclosureGroupName:           EG-3F-VC40F8            
             affinity:                     Bay            
             hideUnusedFlexNics:           True            
             wwnType:                     Virtual         
             macType:                     Virtual         
             serialNumberType:            Virtual         
             bootMode:                               
                 manageMode:              True         
                 mode:                    UEFIOptimized         
                 secureBoot:                      
                 pxeBootPolicy:                   
             boot:                                    
                 manageBoot:              True          
                 order:                               
                     - HardDisk                         
             bios:                                    
                 manageBios:               True         
                 overriddenSettings:                                    
                 - id:         MemPatrolScrubbing              
                   value:      Disabled                 
             firmware:                               
                 manageFirmware:          True         
                 firmwareInstallType:     FirmwareOnlyOfflineMode         
                 forceInstallFirmware:    True         
                 firmwareBaselineName:    HPE Synergy Custom SPP 201912 2020 01 25         
                 firmwareActivationType:  Immediate         


     - name: Add network connection 'Management'  to server profile or template HPE Synergy 480 Gen10 with Local Boot for RSOE Template     
       oneview_server_profile_template:          
         config:     '{{ config }}'                
         state:      present                         
         data:                                       
             name:                          'HPE Synergy 480 Gen10 with Local Boot for RSOE Template'   
             type:                          'ServerProfileTemplateV7'   
             connectionSettings:                     
                 manageConnections:          True      
                 connections:                        
                     - id:                   1      
                       portId:               Auto      
                       name:                 MGMT_A      
                       functionType:         Ethernet      
                       networkName:          Management      
                       requestedMbps:        4000      
                     - id:                   2      
                       portId:               Auto      
                       name:                 MGMT_B      
                       functionType:         Ethernet      
                       networkName:          Management      
                       requestedMbps:        4000      
                     - id:                   3      
                       portId:               Auto      
                       name:                 PROD_A      
                       functionType:         Ethernet      
                       networkName:          Production Networks      
                       requestedMbps:        10000      
                     - id:                   4      
                       portId:               Auto      
                       name:                 PROD_B      
                       functionType:         Ethernet      
                       networkName:          Production Networks      
                       requestedMbps:        10000      
                     - id:                   5      
                       portId:               Auto      
                       name:                 FC_A      
                       functionType:         FibreChannel      
                       networkName:          FC_A      
                       requestedMbps:        16000      
                     - id:                   6      
                       portId:               Auto      
                       name:                 FC_B      
                       functionType:         FibreChannel      
                       networkName:          FC_B      
                       requestedMbps:        16000      
                                                     
     - name: Add local storage 'Embedded' to server profile or template HPE Synergy 480 Gen10 with Local Boot for RSOE Template    
       oneview_server_profile_template:          
         config:     '{{ config }}'                
         state:      present                         
         data:                                       
             name:                          'HPE Synergy 480 Gen10 with Local Boot for RSOE Template'   
             type:                          'ServerProfileTemplateV7'  
             localStorage:                           
                 controllers:                        
                     - deviceSlot:           Embedded      
                       driveWriteCache:      Enabled      
                       initialize:           True      
                       mode:                 Mixed      
                       logicalDrives:                
                         - name:                 ld2  
                           accelerator:          Unmanaged  
                           bootable:             False  
                           driveTechnology:      SataHdd  
                           numPhysicalDrives:    2  
                           raidLevel:            RAID1  
       delegate_to: localhost                    

