---
- hosts: all
  connection: local
  vars:
    # config: "{{ playbook_dir }}/oneview_config.json"
    # server_profile_template_name: SPT-VCF40-VSAN-created-with-ansible
    server_profile_name: esx11.vcf.obs.hpecic.net-VCF-VI-PRIMERA
    #server_hardware_type_name: SY 480 Gen10 1
    enclosure_group_name: SynFrame20-30_EG
    #server_profile_name: RHEL8.2
  tasks:
    - name: Gather facts about a Server Profile by name
      oneview_server_profile_facts:
        config: "{{ config }}"
        name: "{{server_profile_name}}"
      delegate_to: localhost

    - debug: var=server_profiles